### PR TITLE
Market orders contract

### PR DESCRIPTION
**Pull request by marcelomorgado**
Refs https://github.com/UniTradeApp/unitrade-app/issues/304

Some notes:
- This new contract uses fee parameters and staker/incinerator contract addresses from `UniTradeOrderBook`;
- The code was based on `UniTradeOrderBook.executeOrder` that calls basic swap functions and those `...SupportingFeeOnTransferTokens` functions when identify that a token collects fee. For the `UniTradeMarketOrders` implementation I've dry the code a little bit by only calling the `...SupportingFeeOnTransferTokens` functions for all tokens (`Uniswap` docs says that it works for all tokens). Is there a reason why the current implementation doesn't do the same?

### CODE REVIEW

**Comment by adamgall** [comment]
> Is there a reason why the current implementation doesn't do the same?

If I remember correctly, it's because of fees. It's more cost efficient to _not_ call that function for regular ERC20 tokens (which don't take a fee on transfer).

**Review by adamgall — COMMENTED** [review]
At first glance, my initial feedback would be to create an interface for the `UniTradeOrderBook`, so that you don't need to include the entire contract in `UniTradeMarketOrders`.

**Comment by marcelomorgado** [comment]
> At first glance, my initial feedback would be to create an interface for the `UniTradeOrderBook`, so that you don't need to include the entire contract in `UniTradeMarketOrders`.
> 
> Same with the `Incinerator`.

I've tried to do so but since I need to get variables (e.g. fee values for `UniTradeOrderBook`), and there are no getter functions for these values, I can't get them using an interface.
Regarding `Incinerator`, I've removed the import since it isn't used.

**Comment by marcelomorgado** [comment]
> > Is there a reason why the current implementation doesn't do the same?
> 
> If I remember correctly, it's because of fees. It's more cost efficient to _not_ call that function for regular ERC20 tokens (which don't take a fee on transfer).

Hi, I've made some tryouts here and here are the results for the same swaps:
```
// swapExactETHForTokens                              = 103853
// swapExactETHForTokensSupportingFeeOnTransferTokens = 111083


// swapExactTokensForTokens                              = 145043
// swapExactTokensForTokensSupportingFeeOnTransferTokens = 153609
```

The `xxxSupportingFeeOnTransferTokens` functions cost about 8k more gas. Do you think that worth to have this increase to having a simpler code or not?

**Comment by adamgall** [comment]
In my opinion, I think it’s fine to use the “SupportingFeeOnTransferTokens” by default, yes.

**Comment by reborn1002** [comment]
Merge this in? @marcelomorgado

**Comment by marcelomorgado** [comment]
> Merge this in? @marcelomorgado

Yes. Merged.

**Pull request merged**
